FROM jenkins:latest
MAINTAINER Sylvain Révéreault

USER root

RUN apt-get update && apt-get install -y apt-transport-https ca-certificates
RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
COPY docker.list /etc/apt/sources.list.d/

RUN apt-get update && apt-get install -y docker-engine
RUN gpasswd -a jenkins docker

USER jenkins
